name: CI
on: [push]
jobs:

  test:
    name: Linters and tests

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run linters and tests based on "docker build" approach
      run: docker build -f Dockerfile.test .
